import Foundation

enum L10n {
    nonisolated(unsafe) static var languageProvider: () -> AppLanguage = { .system }

    static func string(_ key: String) -> String {
        let language = languageProvider()
        if language != .system {
            return dictionary(for: language)[key] ?? key
        }

        let resourceValue = NSLocalizedString(key, comment: "")
        guard resourceValue == key else { return resourceValue }
        return dictionary(for: .system)[key] ?? key
    }

    static func string(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: string(key), arguments: arguments)
    }

    static func string(_ key: String, fallback: String) -> String {
        let value = string(key)
        return value == key ? fallback : value
    }

    static var allKnownKeys: Set<String> {
        Set(english.keys).union(simplifiedChinese.keys)
    }

    static func string(_ key: String, language: AppLanguage) -> String {
        dictionary(for: language)[key] ?? key
    }

    private static func dictionary(for language: AppLanguage) -> [String: String] {
        switch language {
        case .english:
            return english
        case .simplifiedChinese:
            return simplifiedChinese
        case .system:
            return Locale.preferredLanguages.first?.hasPrefix("zh") == true ? simplifiedChinese : english
        }
    }

    private static let english: [String: String] = [
        "app.name": "ClickMate",
        "app.version": "Version %@",
        "app.versionWithBuild": "Version %@ (%@)",
        "app.build": "Build %@",
        "update.check": "Check for Updates",
        "update.checking": "Checking...",
        "update.availableInline": "%@ Available",
        "update.alertAvailableTitle": "Update Available",
        "update.alertAvailableMessage": "ClickMate %@ is available. You are using %@.",
        "update.alertUpToDateTitle": "Up to Date",
        "update.alertUpToDateMessage": "ClickMate %@ is the latest version.",
        "update.alertFailedTitle": "Unable to Check for Updates",
        "update.alertFailedMessage": "ClickMate could not reach GitHub. You can open the Releases page and try again later.",
        "update.openDownload": "Open Download Page",
        "update.openReleases": "Open Releases",
        "update.later": "Later",
        "update.close": "OK",
        "update.notificationTitle": "ClickMate Update Available",
        "update.notificationBody": "ClickMate %@ is available. Open ClickMate to download it.",
        "settings.title": "Settings",
        "settings.language": "Language",
        "language.system": "Follow System",
        "language.english": "English",
        "language.simplifiedChinese": "Simplified Chinese",
        "tab.menus": "Menus",
        "tab.layout": "Layout",
        "tab.templates": "Templates",
        "tab.apps": "Apps",
        "tab.quickFeatures": "Quick Features",
        "tab.permissions": "Permissions",
        "finder.toolbarTooltip": "ClickMate Finder actions",
        "menus.title": "Finder Menu",
        "menus.description": "Enable the commands that should appear under the ClickMate submenu in Finder.",
        "layout.title": "Menu Layout",
        "layout.description": "Choose menu placement and add frequently used actions as top-level Finder shortcuts.",
        "layout.foldIntoApp": "Fold into ClickMate",
        "layout.statusFolded": "Shown under the ClickMate submenu.",
        "layout.statusTopLevel": "Shown directly in the Finder context menu.",
        "layout.topLevelShortcut": "Top-level shortcut",
        "button.enableAll": "Enable All",
        "button.resetDefaults": "Reset Defaults",
        "button.refresh": "Refresh",
        "button.remove": "Remove",
        "button.restoreRemoved": "Restore Removed",
        "templates.title": "New File Templates",
        "templates.description": "Templates are used by the Finder background menu and by selected folders.",
        "templates.customExtension": "Custom extension",
        "templates.addTemplate": "Add Template",
        "apps.title": "Applications",
        "apps.description": "ClickMate detects common terminals and editors. Finder actions use installed apps only.",
        "apps.detected": "Detected",
        "apps.notInstalled": "Not installed",
        "apps.pinned": "Pinned Custom Apps",
        "apps.pinApplication": "Pin Application...",
        "permissions.title": "Permissions",
        "permissions.description": "Follow these steps after installing ClickMate. Finder menus and file access are separate macOS permissions.",
        "permissions.completeGuide": "Done",
        "permissions.stepInstallTitle": "Install in Applications",
        "permissions.stepInstallDescription": "Drag ClickMate.app into Applications before enabling permissions. Running from the DMG can prevent macOS from registering the Finder extension reliably.",
        "permissions.installedInApplications": "Installed",
        "permissions.notInApplications": "Move to Applications",
        "permissions.stepExtensionTitle": "Enable Finder Extension",
        "permissions.stepExtensionDescription": "The right-click menu appears only after the Finder extension is enabled in System Settings.",
        "permissions.openExtensions": "Open Login Items & Extensions",
        "permissions.openLoginItems": "Open Login Items",
        "permissions.openFullDiskAccess": "Open Full Disk Access",
        "permissions.stepLaunchAtLoginTitle": "Launch at Login",
        "permissions.stepBackgroundServiceTitle": "Background Shortcuts",
        "permissions.backgroundServiceDescription": "Runs cut and screenshot shortcuts in a lightweight background helper, even after the settings app quits.",
        "permissions.backgroundServiceToggle": "Enable background shortcuts",
        "permissions.backgroundServiceRunning": "Background service is running.",
        "permissions.backgroundServiceRunningDirect": "Background service is running for this login session.",
        "permissions.backgroundServiceNotRunning": "Background service is enabled but not responding.",
        "permissions.backgroundServiceDisabled": "Background service is disabled.",
        "permissions.backgroundServiceRequiresApproval": "Approval is required in Login Items.",
        "permissions.backgroundServiceUnavailable": "Background service is unavailable.",
        "permissions.backgroundServiceManagedFallback": "Login Item registration is unavailable. ClickMate is using a session-only background service.",
        "permissions.backgroundServiceDirectSession": "Unsigned build: shortcuts remain available after quitting ClickMate, but you must reopen ClickMate after logging out or restarting.",
        "permissions.backgroundServiceDirectLaunchFailed": "Could not start ClickMate Background Service.",
        "permissions.backgroundServiceConfigurationFailed": "Could not prepare the background service configuration.",
        "permissions.backgroundServiceCleanupDeferred": "The previous Login Item could not be removed now; the current background session is unaffected.",
        "permissions.backgroundServiceRuntimeDetails": "PID %d · %@ · heartbeat %@",
        "permissions.helperPermissionUnknown": "Permission status is unknown because the background service is not running.",
        "permissions.helperPermissionRefreshing": "Refreshing ClickMate Background Service permission…",
        "permissions.restartBackgroundService": "Restart Background Service",
        "permissions.repairBackgroundService": "Repair Background Service",
        "permissions.helperPermissionMigration": "Cut and screenshot permissions now belong to ClickMate Background Service. Please grant them again once.",
        "permissions.launchAtLoginDescription": "Start ClickMate automatically after you sign in.",
        "permissions.launchAtLoginToggle": "Launch ClickMate at login",
        "permissions.launchAtLoginEnabled": "Enabled",
        "permissions.launchAtLoginDisabled": "Disabled",
        "permissions.launchAtLoginRequiresApproval": "Approval required",
        "permissions.launchAtLoginUnavailable": "Unavailable",
        "permissions.launchAtLoginUpdateFailed": "Could not update the launch-at-login setting.",
        "permissions.extensionEnabled": "Enabled",
        "permissions.extensionDisabled": "Disabled",
        "permissions.extensionNotRegistered": "Not registered",
        "permissions.extensionUnknown": "Unknown",
        "permissions.extensionEnabledHint": "Finder extension is enabled. Restart Finder if the menu still does not appear.",
        "permissions.stepDiskAccessTitle": "Grant File Access",
        "permissions.fullDiskAccessGranted": "Full Disk Access is enabled.",
        "permissions.fullDiskAccessMissing": "Full Disk Access is not detected.",
        "permissions.fullDiskAccessDescription": "ClickMate never scans other apps' protected data. Finder menus cover common folders by default; add other folders explicitly when needed.",
        "permissions.fullDiskAccessManualAdd": "If ClickMate is not listed, click + and choose /Applications/ClickMate.app manually.",
        "permissions.fullDiskAccessRestartRequired": "Restart ClickMate to apply the updated system setting.",
        "permissions.fullDiskAccessApplying": "Restarting related processes and applying access…",
        "permissions.fullDiskAccessApplied": "System access reloaded.",
        "permissions.fullDiskAccessAppliedDetail": "ClickMate started in a new process and reloaded Finder Extension. If the switch is enabled in System Settings, future file operations will use the latest authorization.",
        "permissions.fullDiskAccessApplyFailed": "ClickMate restarted, but Finder Extension did not finish reloading. Use Reload Extension above, or restart Finder and try again.",
        "permissions.fullDiskAccessSystemManaged": "Confirm access in System Settings.",
        "permissions.fullDiskAccessExtensionNotReporting": "Finder Extension has not reported its runtime status.",
        "permissions.fullDiskAccessExtensionRunning": "Finder Extension is running. Access is checked only when you perform a file action.",
        "permissions.stepManualFoldersTitle": "Add Manual Folders",
        "permissions.manualFoldersDescription": "Add project or work folders outside the safe defaults. Your home folder and user Library cannot be added.",
        "permissions.manualFoldersStatus": "%d folder(s)",
        "permissions.addFolder": "Add Folder...",
        "permissions.removeFolder": "Remove",
        "permissions.reloadExtension": "Reload Finder Extension",
        "permissions.finderPolicyUpdateRequired": "Finder Extension needs a safe monitoring update.",
        "permissions.finderPolicyReloading": "Updating Finder Extension monitoring…",
        "permissions.finderPolicyReloadFailed": "Could not reload Finder Extension. Reload it manually or restart Finder.",
        "permissions.finderPolicyReloadTimedOut": "Finder Extension did not report the safe monitoring policy. Reload it manually or restart Finder.",
        "permissions.finderRuntimeUnavailableStatus": "Extension status sharing unavailable in this build",
        "permissions.sharedContainerUnavailable": "This build does not have valid App Group authorization, so ClickMate and Finder Extension cannot share settings or runtime status. Install a build signed with Apple Development or Developer ID and an authorized provisioning profile before validating Finder Extension or Full Disk Access.",
        "permissions.finderMonitoringMigration": "ClickMate no longer monitors your entire home folder. Unsafe home and Library entries were removed to prevent repeated App Data prompts.",
        "permissions.monitoredFolders": "Manual Folders",
        "permissions.userDirectory": "User Directory",
        "permissions.extensionStatusUnknown": "If the menu does not appear, enable the Finder extension and reload Finder.",
        "permissions.wideCoverageDescription": "ClickMate covers visible, safe top-level folders in your home directory, such as Desktop, Documents, Downloads, Projects, and Workspace. User Library, hidden folders, external disks, and DMGs are excluded.",
        "permissions.reloadRequested": "Refresh requested. Restart Finder if the menu still does not appear.",
        "permissions.monitoringUpdated": "Monitored folders updated.",
        "permissions.monitoringUpdatedWithSkipped": "Monitored folders updated. Skipped %d unsupported folder(s).",
        "permissions.blockedFolder": "ClickMate cannot monitor your home folder, user Library, or protected system folders.",
        "permissions.bookmarkMissing": "Choose this folder again to refresh manual access.",
        "permissions.footer": "The basic Finder menu covers safe default folders and their contents. User Library, hidden folders, external disks, and DMGs remain excluded unless you explicitly add a supported location.",
        "permissions.stepAccessibilityTitle": "Accessibility",
        "permissions.accessibilityGranted": "Accessibility is enabled.",
        "permissions.accessibilityMissing": "Accessibility is required.",
        "permissions.accessibilityDescription": "Accessibility lets ClickMate translate Finder cut and paste shortcuts without changing shortcuts in other apps.",
        "permissions.openAccessibility": "Open Accessibility Settings",
        "permissions.stepScreenRecordingTitle": "Screen Recording",
        "permissions.screenRecordingGranted": "Screen Recording is enabled.",
        "permissions.screenRecordingMissing": "Screen Recording is required.",
        "permissions.screenRecordingDescription": "Screen Recording lets ClickMate capture a selected region or the display under the pointer.",
        "permissions.openScreenRecording": "Open Screen Recording Settings",
        "permissions.requestAccess": "Request Access",
        "permissions.restartApplication": "Restart and Apply",
        "permissions.restartHint": "If the permission is already enabled in System Settings but is still not detected, restart ClickMate to apply it.",
        "quickFeatures.title": "Quick Features",
        "quickFeatures.description": "Enable built-in actions and assign the global keyboard shortcuts that trigger them.",
        "quickFeatures.finderCutTitle": "Finder Cut",
        "quickFeatures.finderCutDescription": "Use a cut shortcut in Finder, then press Command-V to move the selected files.",
        "quickFeatures.screenshotTitle": "Screenshot",
        "quickFeatures.screenshotDescription": "Capture a region or the current display, then redact and export it.",
        "quickFeatures.shortcut": "Shortcut",
        "quickFeatures.restoreDefault": "Restore Default",
        "quickFeatures.recordShortcut": "Record Shortcut",
        "quickFeatures.recording": "Press a shortcut…",
        "quickFeatures.invalidShortcut": "Use Command or Control with another key.",
        "quickFeatures.duplicateShortcut": "That shortcut is already assigned to another feature.",
        "quickFeatures.registrationFailed": "macOS or another app is already using this shortcut.",
        "quickFeatures.permissionGranted": "Permission granted",
        "quickFeatures.permissionMissing": "Permission required",
        "quickFeatures.permissionUnknown": "Permission unknown",
        "quickFeatures.permissionRefreshing": "Refreshing permission",
        "quickFeatures.backgroundServiceWarning": "Background shortcuts are not running. Enable or repair the background service in Permissions.",
        "button.gotIt": "Got It",
        "quickFeatures.requestPermission": "Request Permission",
        "quickFeatures.openSettings": "Open Settings",
        "quickFeatures.cutNoSelection": "No Finder file is selected.",
        "quickFeatures.cutActivated": "%d item(s) cut. Press ⌘V to move, or ⌘C to copy instead.",
        "quickFeatures.cutPermissionRequired": "Enable Accessibility to use Finder Cut.",
        "quickFeatures.screenshotPermissionRequired": "Enable Screen Recording to take screenshots.",
        "quickFeatures.screenshotInProgress": "A screenshot is already in progress.",
        "screenshot.region": "Region",
        "screenshot.fullScreen": "Full Screen",
        "screenshot.long": "Scrolling Capture",
        "screenshot.longPreview": "Scrolling Capture Preview",
        "screenshot.longPause": "Pause",
        "screenshot.longContinue": "Continue",
        "screenshot.longFinish": "Finish",
        "screenshot.longCapturing": "Scroll downward · %d frames · %d px",
        "screenshot.longPaused": "Capture paused · %d frames · %d px",
        "screenshot.longNoOverlap": "Scroll distance was too large. Scroll up slightly, then continue.",
        "screenshot.longLimitReached": "The scrolling capture reached its size or time limit.",
        "screenshot.edit": "Edit",
        "screenshot.save": "Save As",
        "screenshot.copy": "Copy",
        "screenshot.rectangle": "Rectangle",
        "screenshot.arrow": "Arrow",
        "screenshot.pen": "Pen",
        "screenshot.text": "Text",
        "screenshot.textPlaceholder": "Type text",
        "screenshot.mosaic": "Redact",
        "screenshot.color.red": "Red",
        "screenshot.color.yellow": "Yellow",
        "screenshot.color.green": "Green",
        "screenshot.color.blue": "Blue",
        "screenshot.color.white": "White",
        "screenshot.color.black": "Black",
        "screenshot.size.small": "Small",
        "screenshot.size.medium": "Medium",
        "screenshot.size.large": "Large",
        "screenshot.strength": "Strength",
        "screenshot.undo": "Undo",
        "screenshot.redo": "Redo",
        "screenshot.clear": "Clear",
        "screenshot.copyToClipboard": "Copy to Clipboard",
        "screenshot.saveToDesktop": "Save to Desktop",
        "screenshot.cancel": "Cancel",
        "screenshot.close": "Close",
        "screenshot.done": "Done",
        "screenshot.outputFailed": "The screenshot could not be exported.",
        "screenshot.completed": "Screenshot completed.",
        "screenshot.selectionHint": "Drag to select an area; double-click or press Return to copy",
        "menu.newFile": "New File",
        "menu.newFileTemplates": "New File Templates",
        "menu.copy": "Copy",
        "menu.openHere": "Open Here",
        "menu.openPinned": "Open with Pinned App",
        "menu.hash": "Hash",
        "menu.fileUtilities": "File Utilities",
        "menu.advanced": "Advanced",
        "menu.newFileShortcut": "New %@",
        "command.newFile": "New File",
        "command.copyPOSIXPath": "Copy POSIX Path",
        "command.copyFileURL": "Copy File URL",
        "command.copyShellPath": "Copy Shell-Escaped Path",
        "command.copyFilename": "Copy Filename",
        "command.copyBasename": "Copy Basename",
        "command.copyExtension": "Copy Extension",
        "command.copyParentPath": "Copy Parent Folder Path",
        "command.openTerminal": "Open Terminal Here",
        "command.openITerm": "Open iTerm2 Here",
        "command.openVSCode": "Open in Visual Studio Code",
        "command.openCursor": "Open in Cursor",
        "command.openBBEdit": "Open in BBEdit",
        "command.openSublime": "Open in Sublime Text",
        "command.sha256": "Copy SHA-256",
        "command.sha1": "Copy SHA-1",
        "command.md5": "Copy MD5",
        "command.revealParent": "Reveal Parent Folder",
        "command.duplicateTimestamp": "Duplicate with Timestamp",
        "command.createAlias": "Create Alias",
        "command.moveToNewFolder": "Move to New Folder",
        "command.compress": "Compress",
        "command.metadata": "Copy Metadata Summary",
        "command.imageDimensions": "Copy Image Dimensions",
        "command.toggleHiddenFiles": "Toggle Hidden Files",
        "template.txt": "Text File",
        "template.md": "Markdown",
        "template.json": "JSON",
        "template.csv": "CSV",
        "template.html": "HTML",
        "template.css": "CSS",
        "template.js": "JavaScript",
        "template.swift": "Swift",
        "template.py": "Python",
        "notification.successTitle": "ClickMate",
        "notification.failureTitle": "ClickMate Failed",
        "notification.createdFile": "Created %@",
        "notification.createFailed": "Could not create the file.",
        "notification.permissionRequired": "Enable Full Disk Access for ClickMate or add this folder in Permissions before creating files here.",
        "notification.copied": "Copied to clipboard.",
        "notification.opened": "Opened.",
        "notification.completed": "Completed.",
        "notification.noSelection": "No Finder item is selected.",
        "notification.openFailed": "Could not open the target.",
        "notification.actionFailed": "The action could not be completed."
    ]

    private static let simplifiedChinese: [String: String] = [
        "app.name": "右键大师",
        "app.version": "版本 %@",
        "app.versionWithBuild": "版本 %@ (%@)",
        "app.build": "构建 %@",
        "update.check": "检查更新",
        "update.checking": "正在检查...",
        "update.availableInline": "发现版本 %@",
        "update.alertAvailableTitle": "发现新版本",
        "update.alertAvailableMessage": "ClickMate %@ 已发布，当前版本为 %@。",
        "update.alertUpToDateTitle": "已是最新版本",
        "update.alertUpToDateMessage": "ClickMate %@ 已是最新版本。",
        "update.alertFailedTitle": "无法检查更新",
        "update.alertFailedMessage": "ClickMate 暂时无法访问 GitHub。你可以打开 Releases 页面或稍后重试。",
        "update.openDownload": "前往下载",
        "update.openReleases": "打开 Releases",
        "update.later": "稍后",
        "update.close": "好",
        "update.notificationTitle": "ClickMate 有新版本",
        "update.notificationBody": "ClickMate %@ 已发布，打开 ClickMate 即可前往下载。",
        "settings.title": "设置",
        "settings.language": "语言",
        "language.system": "跟随系统",
        "language.english": "English",
        "language.simplifiedChinese": "简体中文",
        "tab.menus": "菜单",
        "tab.layout": "布局",
        "tab.templates": "模板",
        "tab.apps": "应用",
        "tab.quickFeatures": "快捷功能",
        "tab.permissions": "权限",
        "finder.toolbarTooltip": "右键大师访达操作",
        "menus.title": "访达菜单",
        "menus.description": "选择要显示在访达右键大师右键菜单中的命令。",
        "layout.title": "菜单布局",
        "layout.description": "设置菜单显示层级，并将常用操作添加为访达一级快捷操作。",
        "layout.foldIntoApp": "折叠到右键大师",
        "layout.statusFolded": "显示在右键大师二级菜单下。",
        "layout.statusTopLevel": "直接显示在访达右键一级菜单。",
        "layout.topLevelShortcut": "显示为一级快捷操作",
        "button.enableAll": "全部启用",
        "button.resetDefaults": "恢复默认",
        "button.refresh": "刷新",
        "button.remove": "移除",
        "button.restoreRemoved": "恢复已移除项",
        "templates.title": "新建文件模板",
        "templates.description": "这些模板会用于访达空白处和文件夹右键菜单。",
        "templates.customExtension": "自定义扩展名",
        "templates.addTemplate": "添加模板",
        "apps.title": "应用",
        "apps.description": "右键大师会检测常用终端和编辑器，访达动作只会调用已安装的应用。",
        "apps.detected": "已检测",
        "apps.notInstalled": "未安装",
        "apps.pinned": "固定的自定义应用",
        "apps.pinApplication": "固定应用...",
        "permissions.title": "权限",
        "permissions.description": "安装右键大师后按步骤完成设置。右键菜单和文件访问是两类不同的 macOS 权限。",
        "permissions.completeGuide": "完成引导",
        "permissions.stepInstallTitle": "安装到应用程序",
        "permissions.stepInstallDescription": "请先把 ClickMate.app 拖入“应用程序”再授权。从 DMG 内直接运行可能导致 macOS 无法稳定注册访达扩展。",
        "permissions.installedInApplications": "已安装",
        "permissions.notInApplications": "请移入应用程序",
        "permissions.stepExtensionTitle": "启用访达扩展",
        "permissions.stepExtensionDescription": "只有在系统设置里启用访达扩展后，右键菜单才会出现。",
        "permissions.openExtensions": "打开登录项与扩展",
        "permissions.openLoginItems": "打开登录项",
        "permissions.openFullDiskAccess": "打开完全磁盘访问",
        "permissions.stepLaunchAtLoginTitle": "开机自启",
        "permissions.stepBackgroundServiceTitle": "后台快捷功能",
        "permissions.backgroundServiceDescription": "由轻量后台服务持续运行剪切和截图快捷键，退出设置程序后仍然可用。",
        "permissions.backgroundServiceToggle": "启用后台快捷功能",
        "permissions.backgroundServiceRunning": "后台服务正在运行。",
        "permissions.backgroundServiceRunningDirect": "后台服务正在本次登录会话中运行。",
        "permissions.backgroundServiceNotRunning": "后台服务已启用但没有响应。",
        "permissions.backgroundServiceDisabled": "后台服务已关闭。",
        "permissions.backgroundServiceRequiresApproval": "需要在登录项中允许后台服务。",
        "permissions.backgroundServiceUnavailable": "后台服务不可用。",
        "permissions.backgroundServiceManagedFallback": "系统登录项注册不可用，ClickMate 已改用本次登录会话后台服务。",
        "permissions.backgroundServiceDirectSession": "未签名版本：退出 ClickMate 后快捷功能仍可用，但注销或重启后需要再次打开 ClickMate。",
        "permissions.backgroundServiceDirectLaunchFailed": "无法启动 ClickMate 后台服务。",
        "permissions.backgroundServiceConfigurationFailed": "无法准备后台服务配置。",
        "permissions.backgroundServiceCleanupDeferred": "暂时无法移除旧登录项，不影响当前后台会话。",
        "permissions.backgroundServiceRuntimeDetails": "PID %d · %@ · 心跳 %@",
        "permissions.helperPermissionUnknown": "后台服务未运行，暂时无法确认权限状态。",
        "permissions.helperPermissionRefreshing": "正在刷新 ClickMate 后台服务权限…",
        "permissions.restartBackgroundService": "重启后台服务",
        "permissions.repairBackgroundService": "修复后台服务",
        "permissions.helperPermissionMigration": "剪切和截图权限现在属于“ClickMate 后台服务”，需要重新授权一次。",
        "permissions.launchAtLoginDescription": "登录 Mac 后自动启动右键大师。",
        "permissions.launchAtLoginToggle": "登录时启动右键大师",
        "permissions.launchAtLoginEnabled": "已启用",
        "permissions.launchAtLoginDisabled": "未启用",
        "permissions.launchAtLoginRequiresApproval": "需要系统批准",
        "permissions.launchAtLoginUnavailable": "不可用",
        "permissions.launchAtLoginUpdateFailed": "无法更新开机自启设置。",
        "permissions.extensionEnabled": "已启用",
        "permissions.extensionDisabled": "已停用",
        "permissions.extensionNotRegistered": "未注册",
        "permissions.extensionUnknown": "未知",
        "permissions.extensionEnabledHint": "访达扩展已启用。如果菜单仍未出现，请重启访达。",
        "permissions.stepDiskAccessTitle": "授予文件访问权限",
        "permissions.fullDiskAccessGranted": "已启用完全磁盘访问。",
        "permissions.fullDiskAccessMissing": "未检测到完全磁盘访问。",
        "permissions.fullDiskAccessDescription": "ClickMate 不会扫描其他 App 的受保护数据。访达菜单默认覆盖常用安全目录，其他目录需要时请手动添加。",
        "permissions.fullDiskAccessManualAdd": "如果列表里没有右键大师，请点击 +，手动选择 /Applications/ClickMate.app。",
        "permissions.fullDiskAccessRestartRequired": "需要重新启动右键大师以应用更新后的系统设置。",
        "permissions.fullDiskAccessApplying": "正在重新启动相关进程并应用权限…",
        "permissions.fullDiskAccessApplied": "系统权限已重新加载。",
        "permissions.fullDiskAccessAppliedDetail": "ClickMate 已使用新进程启动，并重新加载了 Finder Extension。如果系统设置中的开关已开启，后续文件访问会直接使用最新授权。",
        "permissions.fullDiskAccessApplyFailed": "ClickMate 已重新启动，但 Finder Extension 未能完成重新加载。请点击上方“重新加载扩展”，或重新启动 Finder 后再试。",
        "permissions.fullDiskAccessSystemManaged": "请在系统设置中确认权限。",
        "permissions.fullDiskAccessExtensionNotReporting": "访达扩展尚未报告运行状态。",
        "permissions.fullDiskAccessExtensionRunning": "访达扩展正在运行；仅在你执行文件操作时检查实际访问能力。",
        "permissions.stepManualFoldersTitle": "添加手动文件夹",
        "permissions.manualFoldersDescription": "可添加安全默认范围之外的项目或工作目录；不能添加用户主目录和用户 Library。",
        "permissions.manualFoldersStatus": "%d 个文件夹",
        "permissions.addFolder": "添加文件夹...",
        "permissions.removeFolder": "移除",
        "permissions.reloadExtension": "重新加载访达扩展",
        "permissions.finderPolicyUpdateRequired": "Finder Extension 需要更新安全监控策略。",
        "permissions.finderPolicyReloading": "正在更新 Finder Extension 监控策略…",
        "permissions.finderPolicyReloadFailed": "无法重新加载 Finder Extension，请手动重载或重启访达。",
        "permissions.finderPolicyReloadTimedOut": "Finder Extension 未报告安全监控策略，请手动重载或重启访达。",
        "permissions.finderRuntimeUnavailableStatus": "当前构建不支持扩展状态共享",
        "permissions.sharedContainerUnavailable": "当前构建缺少有效的 App Group 授权，无法在 ClickMate 与 Finder Extension 之间共享设置和运行状态。请安装使用 Apple Development 或 Developer ID 身份签名并包含授权描述文件的版本后，再验证 Finder Extension 和完全磁盘访问。",
        "permissions.finderMonitoringMigration": "ClickMate 不再监控整个用户主目录。为避免反复出现 App 数据弹窗，已移除主目录和用户 Library 的旧配置。",
        "permissions.monitoredFolders": "手动文件夹",
        "permissions.userDirectory": "用户目录",
        "permissions.extensionStatusUnknown": "如果右键菜单没有出现，请启用访达扩展并重新加载访达。",
        "permissions.wideCoverageDescription": "默认覆盖用户目录下可见的安全一级目录，例如桌面、文稿、下载、Projects 和 Workspace；不包含用户 Library、隐藏目录、外接磁盘和 DMG。",
        "permissions.reloadRequested": "已请求刷新。如果菜单仍未出现，请重启访达。",
        "permissions.monitoringUpdated": "监控文件夹已更新。",
        "permissions.monitoringUpdatedWithSkipped": "监控文件夹已更新，已跳过 %d 个不支持的文件夹。",
        "permissions.blockedFolder": "ClickMate 不能监控用户主目录、用户 Library 或受保护的系统文件夹。",
        "permissions.bookmarkMissing": "请重新选择此文件夹以刷新手动授权。",
        "permissions.footer": "基础访达菜单覆盖安全默认目录及其子目录；用户 Library、隐藏目录、外接磁盘和 DMG 需要保持排除或由你明确添加。",
        "permissions.stepAccessibilityTitle": "辅助功能",
        "permissions.accessibilityGranted": "已启用辅助功能权限。",
        "permissions.accessibilityMissing": "需要辅助功能权限。",
        "permissions.accessibilityDescription": "辅助功能权限用于在访达中转换剪切和粘贴快捷键，不会修改其他应用的快捷键。",
        "permissions.openAccessibility": "打开辅助功能设置",
        "permissions.stepScreenRecordingTitle": "屏幕录制",
        "permissions.screenRecordingGranted": "已启用屏幕录制权限。",
        "permissions.screenRecordingMissing": "需要屏幕录制权限。",
        "permissions.screenRecordingDescription": "屏幕录制权限用于截取区域或鼠标所在显示器。",
        "permissions.openScreenRecording": "打开屏幕录制设置",
        "permissions.requestAccess": "请求权限",
        "permissions.restartApplication": "重新启动并应用",
        "permissions.restartHint": "如果已在系统设置中开启但仍未检测到，请重新启动右键大师使权限生效。",
        "quickFeatures.title": "快捷功能",
        "quickFeatures.description": "启用系统内置功能，并设置用于触发它们的全局快捷键。",
        "quickFeatures.finderCutTitle": "访达剪切",
        "quickFeatures.finderCutDescription": "在访达中剪切所选文件，再按 Command-V 将文件移动到当前位置。",
        "quickFeatures.screenshotTitle": "截图",
        "quickFeatures.screenshotDescription": "截取区域或当前显示器，打码后复制或保存。",
        "quickFeatures.shortcut": "快捷键",
        "quickFeatures.restoreDefault": "恢复默认",
        "quickFeatures.recordShortcut": "录制快捷键",
        "quickFeatures.recording": "请按下快捷键…",
        "quickFeatures.invalidShortcut": "请使用 Command 或 Control 与其他按键组合。",
        "quickFeatures.duplicateShortcut": "该快捷键已分配给其他功能。",
        "quickFeatures.registrationFailed": "该快捷键已被 macOS 或其他应用占用。",
        "quickFeatures.permissionGranted": "权限已授予",
        "quickFeatures.permissionMissing": "需要权限",
        "quickFeatures.permissionUnknown": "权限状态未知",
        "quickFeatures.permissionRefreshing": "正在刷新权限",
        "quickFeatures.backgroundServiceWarning": "后台快捷功能没有运行，请在权限页面启用或修复后台服务。",
        "button.gotIt": "知道了",
        "quickFeatures.requestPermission": "请求权限",
        "quickFeatures.openSettings": "打开设置",
        "quickFeatures.cutNoSelection": "没有选择访达文件。",
        "quickFeatures.cutActivated": "已剪切 %d 个项目；按 ⌘V 移动，按 ⌘C 改为复制。",
        "quickFeatures.cutPermissionRequired": "请启用辅助功能权限后使用访达剪切。",
        "quickFeatures.screenshotPermissionRequired": "请启用屏幕录制权限后使用截图。",
        "quickFeatures.screenshotInProgress": "截图正在进行。",
        "screenshot.region": "区域",
        "screenshot.fullScreen": "全屏",
        "screenshot.long": "长截图",
        "screenshot.longPreview": "长截图预览",
        "screenshot.longPause": "暂停",
        "screenshot.longContinue": "继续",
        "screenshot.longFinish": "完成",
        "screenshot.longCapturing": "向下滚动 · %d 帧 · %d 像素",
        "screenshot.longPaused": "已暂停 · %d 帧 · %d 像素",
        "screenshot.longNoOverlap": "滚动幅度过大，请向上回滚一点后继续。",
        "screenshot.longLimitReached": "长截图已达到尺寸或时间上限。",
        "screenshot.edit": "编辑",
        "screenshot.save": "另存为",
        "screenshot.copy": "复制",
        "screenshot.rectangle": "矩形",
        "screenshot.arrow": "箭头",
        "screenshot.pen": "画笔",
        "screenshot.text": "文字",
        "screenshot.textPlaceholder": "输入文字",
        "screenshot.mosaic": "打码",
        "screenshot.color.red": "红色",
        "screenshot.color.yellow": "黄色",
        "screenshot.color.green": "绿色",
        "screenshot.color.blue": "蓝色",
        "screenshot.color.white": "白色",
        "screenshot.color.black": "黑色",
        "screenshot.size.small": "细",
        "screenshot.size.medium": "中",
        "screenshot.size.large": "粗",
        "screenshot.strength": "强度",
        "screenshot.undo": "撤销",
        "screenshot.redo": "重做",
        "screenshot.clear": "清除",
        "screenshot.copyToClipboard": "复制到剪贴板",
        "screenshot.saveToDesktop": "保存到桌面",
        "screenshot.cancel": "取消",
        "screenshot.close": "关闭",
        "screenshot.done": "完成",
        "screenshot.outputFailed": "无法导出截图。",
        "screenshot.completed": "截图已完成。",
        "screenshot.selectionHint": "拖动选择区域，双击或按回车复制",
        "menu.newFile": "新建文件",
        "menu.newFileTemplates": "新建文件模板",
        "menu.copy": "复制",
        "menu.openHere": "在此处打开",
        "menu.openPinned": "用固定应用打开",
        "menu.hash": "哈希",
        "menu.fileUtilities": "文件工具",
        "menu.advanced": "高级",
        "menu.newFileShortcut": "新建 %@",
        "command.newFile": "新建文件",
        "command.copyPOSIXPath": "复制 POSIX 路径",
        "command.copyFileURL": "复制文件 URL",
        "command.copyShellPath": "复制 Shell 转义路径",
        "command.copyFilename": "复制文件名",
        "command.copyBasename": "复制主文件名",
        "command.copyExtension": "复制扩展名",
        "command.copyParentPath": "复制父文件夹路径",
        "command.openTerminal": "在此处打开终端",
        "command.openITerm": "在此处打开 iTerm2",
        "command.openVSCode": "用 Visual Studio Code 打开",
        "command.openCursor": "用 Cursor 打开",
        "command.openBBEdit": "用 BBEdit 打开",
        "command.openSublime": "用 Sublime Text 打开",
        "command.sha256": "复制 SHA-256",
        "command.sha1": "复制 SHA-1",
        "command.md5": "复制 MD5",
        "command.revealParent": "显示父文件夹",
        "command.duplicateTimestamp": "带时间戳复制",
        "command.createAlias": "制作替身",
        "command.moveToNewFolder": "移到新文件夹",
        "command.compress": "压缩",
        "command.metadata": "复制元数据摘要",
        "command.imageDimensions": "复制图片尺寸",
        "command.toggleHiddenFiles": "切换隐藏文件显示",
        "template.txt": "文本文件",
        "template.md": "Markdown",
        "template.json": "JSON",
        "template.csv": "CSV",
        "template.html": "HTML",
        "template.css": "CSS",
        "template.js": "JavaScript",
        "template.swift": "Swift",
        "template.py": "Python",
        "notification.successTitle": "右键大师",
        "notification.failureTitle": "右键大师失败",
        "notification.createdFile": "已创建 %@",
        "notification.createFailed": "无法创建文件。",
        "notification.permissionRequired": "请为右键大师开启完全磁盘访问，或在权限中添加此文件夹后再创建文件。",
        "notification.copied": "已复制到剪贴板。",
        "notification.opened": "已打开。",
        "notification.completed": "已完成。",
        "notification.noSelection": "没有选择访达项目。",
        "notification.openFailed": "无法打开目标。",
        "notification.actionFailed": "无法完成此操作。"
    ]
}
